const HTTP_STATUS_CODES = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};
const SORTING = { ASC: 'asc', DECS: 'desc' };
const RESPONSE_DATA_LIMIT = 150;

module.exports = { HTTP_STATUS_CODES, SORTING, RESPONSE_DATA_LIMIT };
